config/routes.rb
Rails.application.routes.draw do
  namespace :users, path: 'app' do
    resources :projects do
      resources :tasks, except: [:index] do
        member do
          post :complete, action: :complete
          post :update_weight, action: :update_weight
        end
      end

      member do
        post :update_weight, action: :update_weight
      end
    end
  end

  devise_for :users
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id         :bigint           not null, primary key
#  color      :string
#  name       :string
#  weight     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#
class Project < ApplicationRecord
  has_many :tasks, dependent: :destroy
  belongs_to :user
  positioned on: :user, column: :weight

  def active_tasks
    self
      .tasks
      .order(weight: :asc)
      .where(is_completed: false)
  end
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id           :bigint           not null, primary key
#  description  :text
#  is_completed :boolean          default(FALSE)
#  name         :string
#  weight       :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  project_id   :integer
#  user_id      :integer
#
class Task < ApplicationRecord
  belongs_to :project
  positioned on: :project, column: :weight
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects, dependent: :destroy
  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def after_sign_in_path_for(resource)
    users_projects_path
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users/application_controller.rb
class Users::ApplicationController < ApplicationController
  layout 'users'
  before_action :authenticate_user!
  before_action :set_projects

  private

  def set_projects
    @projects = current_user.projects.order(weight: :asc)
  end
end

app/controllers/users/projects_controller.rb
class Users::ProjectsController < Users::ApplicationController
  skip_before_action :verify_authenticity_token, only: [:update_weight]

  def index
  end

  def new
    @project = Project.new
  end

  def edit
    @project = current_user.projects.find(params[:id])
  end

  def create
    @project = current_user.projects.new(project_params)

    if @project.save
      redirect_to users_projects_path
    else
      render 'new'
    end
  end

  def update
    @project = current_user.projects.find(params[:id])

    if @project.update(project_params)
      redirect_to users_projects_path
    else
      render 'edit'
    end
  end

  def show
    @show_task = params[:show_task] == 'true'
    @project = current_user.projects.find(params[:id])
    @tasks = @project.active_tasks
  end

  def destroy
    @project = current_user.projects.find(params[:id])
    @project.destroy
    redirect_to users_projects_path, status: :see_other
  end

  def update_weight
    @project = current_user.projects.find(params[:id])
    @project.update!(weight: params[:weight])
  end

  private

  def project_params
    params.require(:project).permit(:name)
  end
end

app/controllers/users/tasks_controller.rb
class Users::TasksController < Users::ApplicationController
  skip_before_action :verify_authenticity_token, only: [:update_weight]

  def new
    @project = current_user.projects.find(params[:project_id])
    @task = Task.new
  end

  def edit
    @project = current_user.projects.find(params[:project_id])
    @task = current_user.tasks.find(params[:id])
  end

  def create
    @project = current_user.projects.find(params[:project_id])
    @task = current_user.tasks.new(task_params)
    @task.project_id = @project.id

    if @task.save
      @tasks = @project.active_tasks
      @new_task = Task.new
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    @project = current_user.projects.find(params[:project_id])
    @task = current_user.tasks.find(params[:id])

    if @task.update(task_params)
      @tasks = @project.active_tasks
      @new_task = Task.new
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @project = current_user.projects.find(params[:project_id])
    @tasks = @project.active_tasks
    @task = current_user.tasks.find(params[:id])
    @task.destroy
  end

  def complete
    @project = current_user.projects.find(params[:project_id])
    @tasks = @project.active_tasks
    @task = current_user.tasks.find(params[:id])
    @task.update!(is_completed: true)
  end

  def update_weight
    @project = current_user.projects.find(params[:project_id])
    @task = current_user.tasks.find(params[:id])
    @task.update!(weight: params[:weight])
  end

  private

  def task_params
    params.require(:task).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heroicon_helper.rb
# frozen_string_literal: true

module HeroiconHelper
  include Heroicon::Engine.helpers
end

app/views/layouts/_flash_messages.html.erb
<% if flash[:alert].present? %>
  <div class="rounded-md bg-red-50 p-4 mb-8 border border-red-300">
    <div class="flex">
      <div class="flex-shrink-0">
        <svg class="h-5 w-5 text-red-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.28 7.22a.75.75 0 00-1.06 1.06L8.94 10l-1.72 1.72a.75.75 0 101.06 1.06L10 11.06l1.72 1.72a.75.75 0 101.06-1.06L11.06 10l1.72-1.72a.75.75 0 00-1.06-1.06L10 8.94 8.28 7.22z" clip-rule="evenodd" />
        </svg>
      </div>
      <div class="ml-3">
        <div class="text-sm text-red-700">
          <%= flash[:alert] %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<% if flash[:notice].present? %>
  <div class="rounded-md bg-green-50 p-4 mb-8 border border-green-400">
    <div class="flex">
      <div class="flex-shrink-0">
        <svg class="h-5 w-5 text-green-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z" clip-rule="evenodd" />
        </svg>
      </div>
      <div class="ml-3">
        <div class="text-sm text-green-700">
          <%= flash[:notice] %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full">
  <head>
    <title>DoList: A free and open source alternative to Todoist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" href="/favicon.ico?v=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application" %>

    <script defer data-domain="dolistapp.org" src="https://plausible.io/js/script.js"></script>
  </head>

  <body class="h-full">
    <%= yield %>
  </body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html class="h-full">
  <head>
    <title>DoList: A free and open source alternative to Todoist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" href="/favicon.ico?v=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application" %>

    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.13.3/jquery-ui.min.js" integrity="sha256-sw0iNNXmOJbQhYFuC9OF2kOlD5KQKe1y5lfBn4C9Sjg=" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/@hotwired/turbo@8.0.5/dist/turbo.es2017-umd.js"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
  </head>

  <body class="h-full">
    <div class="flex h-full">
      <div class="bg-zinc-800 text-white text-sm p-5 min-w-[300px]">
        <div class="mb-10">
          <div><%= current_user.email %></div>
          <div><%= link_to 'Logout', destroy_user_session_path, data: { turbo_prefetch: false } %></div>
        </div>

        <%= render 'layouts/users/projects', projects: @projects %>
      </div>

      <div class="bg-zinc-900 text-white grow p-5 overflow-scroll">
        <%= yield %>

        <%= turbo_frame_tag 'modal' %>
      </div>
    </div>

    <script>
      $('[data-sortable-projects]').sortable({
        placeholder: 'sortable-placeholder',

        update(event, ui) {
          const index = ui.item.index();
          const projectId = ui.item.data('project-id');

          fetch(`/app/projects/${projectId}/update_weight`, {
            method: 'POST',
            body: JSON.stringify({ weight: index + 1 }),
            headers: {
              "Content-Type": "application/json",
            }
          });
        }
      })
    </script>
  </body>
</html>

app/views/layouts/users/_projects.html.erb
<% active_list = is_active_link?(users_projects_path, :exact) %>
<% active_list_classes = class_names(
  'bg-[#472525]' => active_list
) %>
<div class="flex justify-between items-center mb-1 rounded-lg <%= active_list_classes %>">
  <%= link_to 'My Projects', users_projects_path, class: 'grow p-2' %>

  <div class="mr-2">
    <%= link_to new_users_project_path, data: { turbo_frame: 'modal' } do %>
      <%= heroicon 'plus', options: { class: 'text-white w-4 h-4' } %>
    <% end %>
  </div>
</div>

<div data-sortable-projects>
  <% projects.each do |project| %>
    <% active_project = is_active_link?(users_project_path(project)) %>
    <% classes = class_names(
        'bg-[#472525] text-red-300' => active_project,
        'hover:bg-zinc-700/25' => !active_project
       )
    %>

    <div x-data="{ open: false }" class="group mb-1 relative flex justify-between items-center rounded-lg <%= classes %>" data-project-id="<%= project.id %>">
      <%= link_to project.name,
          users_project_path(project),
          class: 'block grow p-2'
      %>

      <div class="group-hover:hidden text-[12px] text-zinc-500 mr-3.5">
        <% tasks_count = project.active_tasks.count %>
        <%= tasks_count if tasks_count > 0 %>
      </div>

      <div class="group-hover:flex hidden h-5 items-center relative hover:bg-zinc-700 rounded mr-2 text-white">
        <%= heroicon 'ellipsis-horizontal',
            options: {
              class: 'h-6 w-6 text-zinc-100 cursor-pointer',
              '@click' => 'open = !open; $event.preventDefault();',
              '@click.outside' => 'open = false'
            }
        %>
      </div>

      <div x-show="open" x-cloak class="absolute top-10 right-0 min-w-[200px] z-10 rounded-xl border border-zinc-600 bg-zinc-800 text-zinc-300">
        <div class="divide-y divide-zinc-700">
          <div class="px-1.5 py-1.5">
            <%= link_to edit_users_project_path(project), class: 'flex gap-2 items-center text-[13px] py-2 px-3 hover:bg-zinc-700 rounded', data: { turbo_frame: 'modal' } do %>
              <%= heroicon 'pencil-square', options: { class: 'h-5 w-5 text-slate-100' } %>
              <span>Edit</span>
            <% end %>
          </div>

          <div class="px-1.5 py-1.5">
            <%= link_to users_project_path(project), class: 'flex gap-2 items-center text-[13px] py-2 px-3 hover:bg-zinc-700 rounded', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } do %>
              <%= heroicon 'trash', options: { class: 'h-5 w-5 text-slate-100' } %>
              <span>Delete</span>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="container mx-auto mt-28 px-5">
  <h1 class="font-bold text-8xl mb-3 tracking-tighter">DoList.</h1>
  <p class="text-gray-800 text-xl tracking-tight">
    A free and open-source Todoist alternative
  </p>

  <div class="mt-10 flex items-center gap-x-6">
    <%= link_to 'Sign Up',
        new_user_registration_path,
        class: 'rounded-md bg-indigo-600 px-3.5 py-2.5 font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600'
    %>

    <%= link_to 'Sign In',
        new_user_session_path,
        class: 'rounded-md bg-white px-3.5 py-2.5 font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50'
    %>
  </div>
</div>

app/views/shared/_modal.html.erb
<div class="relative z-10" aria-labelledby="modal-title" role="dialog" aria-modal="true">
  <div class="fixed inset-0 bg-black bg-opacity-75 transition-opacity" aria-hidden="true"></div>

  <div class="fixed inset-0 z-10 w-screen overflow-y-auto">
    <div class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
      <div class="relative transform overflow-hidden rounded-lg bg-zinc-900 border border-zinc-700 px-4 pb-4 pt-5 text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-sm sm:p-6">
        <%= yield %>
      </div>
    </div>
  </div>
</div>

app/views/users/projects/_tasks.html.erb
<div id="tasks">
  <% if tasks.any? %>
    <div class="mb-3" data-sortable-tasks>
      <% tasks.each do |task| %>
        <%= turbo_frame_tag "#{dom_id(task)}_edit", class: 'group block bg-zinc-900 border-b border-b-zinc-700 relative flex justify-between items-center py-2', data: { task_id: task.id } do %>
          <div class="opacity-0 group-hover:opacity-100 absolute -left-[25px] pr-[5px]">
            <%= heroicon 'bars-3', options: { class: 'h-5 w-5 cursor-move text-zinc-300', data_handle: true } %>
          </div>

          <div class="flex items-center gap-2">
            <%= link_to complete_users_project_task_path(@project, task), data: { turbo_method: :post }, class: 'group/check w-[18px] h-[18px] rounded-full border border-zinc-400' do %>
              <%= heroicon 'check', options: { class: 'group-hover/check:opacity-100 opacity-0 transition-opacity duration-200 text-zinc-400 w-3 h-3 mt-[2px] ml-[2px]' } %>
            <% end %>

            <div class="text-sm text-zinc-200">
              <%= task.name %>
            </div>
          </div>

          <div x-data="{ open: false }" class="h-5 flex items-center relative hover:bg-zinc-700 rounded">
            <%= heroicon 'ellipsis-horizontal',
                options: {
                  class: 'h-8 w-8 text-slate-100 cursor-pointer',
                  '@click' => 'open = true',
                  '@click.outside' => 'open = false'
                }
            %>

            <div x-show="open" x-cloak class="absolute top-6 right-0 min-w-[200px] z-10 rounded-xl border border-zinc-600 bg-zinc-800">
              <div class="divide-y divide-zinc-700">
                <div class="px-1.5 py-1.5">
                  <%= link_to edit_users_project_task_path(@project, task), class: 'flex gap-2 items-center text-[13px] py-2 px-3 hover:bg-zinc-700 rounded' do %>
                    <%= heroicon 'pencil-square', options: { class: 'h-5 w-5 text-slate-100' } %>
                    <span>Edit</span>
                  <% end %>
                </div>

                <div class="px-1.5 py-1.5">
                  <%= link_to users_project_task_path(@project, task), class: 'flex gap-2 items-center text-[13px] py-2 px-3 hover:bg-zinc-700 rounded', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } do %>
                    <%= heroicon 'trash', options: { class: 'h-5 w-5 text-slate-100' } %>
                    <span>Delete</span>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

<script>
  $('[data-sortable-tasks]').sortable({
    handle: '[data-handle]',
    placeholder: 'sortable-placeholder',

    update(event, ui) {
      const index = ui.item.index();
      const taskId = ui.item.data('task-id');

      fetch(`/app/projects/<%= @project.id %>/tasks/${taskId}/update_weight`, {
        method: 'POST',
        body: JSON.stringify({ weight: index + 1 }),
        headers: {
          "Content-Type": "application/json",
        }
      });
    }
  })
</script>

app/views/users/projects/edit.html.erb
<%= turbo_frame_tag 'modal' do %>
  <%= render 'shared/modal' do %>
    <div class="font-semibold text-lg mb-5">
      Edit
    </div>

    <div>
      <%= form_for(@project, url: users_project_path(@project), data: { turbo_frame: '_top' }) do |f| %>
        <div class="mb-5">
          <%= f.label :name, class: 'block text-sm mb-1' %>

          <%= f.text_field :name,
              autofocus: true,
              required: true,
              class: 'w-full bg-transparent border-zinc-700 p-1 text-sm rounded'
          %>
        </div>

        <div class="flex gap-3">
          <%= button_tag 'Cancel',
              type: 'button',
              class: 'bg-zinc-800 py-1.5 px-4 rounded text-sm',
              'x-on:click' => '$("#modal").html("").removeAttr("src")'
          %>

          <%= f.button 'Save', class: 'bg-red-500 py-1.5 px-4 rounded text-sm' %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/users/projects/index.html.erb
<div class="flex flex-col items-center">
  <div class="w-full max-w-3xl mt-10">
    <h1 class="font-semibold text-2xl max-w-xl mb-10">
      My Projects
    </h1>

    <% if @projects.any? %>
      <div class="border-zinc-800 border-b text-sm py-2 my-4 font-semibold">
        <%= pluralize(@projects.count, 'Project') %>
      </div>

      <% @projects.each do |project| %>
        <div x-data="{ open: false }" class="group flex items-center justify-between relative hover:bg-zinc-800 rounded-lg pr-4">
          <%= link_to project.name,
              users_project_path(project),
              class: 'py-4 px-4 text-sm block grow'
          %>

          <div class="group-hover:flex hidden h-6 items-center relative hover:bg-zinc-700 rounded mr-2 text-white">
            <%= heroicon 'ellipsis-horizontal',
                options: {
                  class: 'h-8 w-8 text-zinc-100 cursor-pointer',
                  '@click' => 'open = !open; $event.preventDefault();',
                  '@click.outside' => 'open = false'
                }
            %>
          </div>

          <div x-show="open" x-cloak class="absolute top-10 right-0 min-w-[200px] z-10 rounded-xl border border-zinc-600 bg-zinc-800 text-zinc-300">
            <div class="divide-y divide-zinc-700">
              <div class="px-1.5 py-1.5">
                <%= link_to edit_users_project_path(project), class: 'flex gap-2 items-center text-[13px] py-2 px-3 hover:bg-zinc-700 rounded', data: { turbo_frame: 'modal' } do %>
                  <%= heroicon 'pencil-square', options: { class: 'h-5 w-5 text-slate-100' } %>
                  <span>Edit</span>
                <% end %>
              </div>

              <div class="px-1.5 py-1.5">
                <%= link_to users_project_path(project), class: 'flex gap-2 items-center text-[13px] py-2 px-3 hover:bg-zinc-700 rounded', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } do %>
                  <%= heroicon 'trash', options: { class: 'h-5 w-5 text-slate-100' } %>
                  <span>Delete</span>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <div>
        No projects.
      </div>
    <% end %>
  </div>
</div>

app/views/users/projects/new.html.erb
<%= turbo_frame_tag 'modal' do %>
  <%= render 'shared/modal' do %>
    <div class="font-semibold text-lg mb-5">
      Add Project
    </div>

    <div>
      <%= form_for(@project, url: users_projects_path, data: { turbo_frame: '_top'}) do |f| %>
        <div class="mb-5">
          <%= f.label :name, class: 'block text-sm mb-1' %>

          <%= f.text_field :name,
              autofocus: true,
              required: true,
              class: 'w-full bg-transparent border-zinc-700 p-1 text-sm rounded'
          %>
        </div>

        <div class="flex gap-3">
          <%= button_tag 'Cancel',
              type: 'button',
              class: 'bg-zinc-800 py-1.5 px-4 rounded text-sm',
              'x-on:click' => '$("#modal").html("").removeAttr("src")'
          %>

          <%= f.button 'Add', class: 'bg-red-500 py-1.5 px-4 rounded text-sm' %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/users/projects/show.html.erb
<div class="flex flex-col items-center">
  <div class="w-full max-w-3xl mt-10">
    <h1 class="font-semibold text-2xl max-w-xl mb-4">
      <%= @project.name %>
    </h1>

    <%= render 'tasks', tasks: @tasks %>

    <%= turbo_frame_tag 'new_task_frame' do %>
      <%= link_to new_users_project_task_path(project_id: @project.id), class: 'group' do %>
        <div class="flex gap-2">
          <%= heroicon 'plus', options: { class: 'text-red-500 w-5 h-5 rounded-full group-hover:text-white group-hover:bg-red-500' } %>

          <div class="text-sm text-gray-500 group-hover:text-red-500">
            Add Task
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/tasks/complete.turbo_stream.erb
<%= turbo_stream.replace "tasks" do %>
  <%= render 'users/projects/tasks', tasks: @tasks %>
<% end %>

app/views/users/tasks/create.turbo_stream.erb
<%= turbo_stream.replace "tasks" do %>
  <%= render 'users/projects/tasks', tasks: @tasks %>
<% end %>

<%= turbo_stream.update "new_task_frame" do %>
  <%= render 'users/tasks/new/form', task: @new_task, project: @project %>
<% end %>

app/views/users/tasks/destroy.turbo_stream.erb
<%= turbo_stream.replace "tasks" do %>
  <%= render 'users/projects/tasks', tasks: @tasks %>
<% end %>

app/views/users/tasks/edit.html.erb
<%= turbo_frame_tag "#{dom_id(@task)}_edit" do %>
  <%= form_for(@task, url: users_project_task_path(@project, @task), html: { class: 'w-full' }) do |f| %>
    <div class="rounded-xl border border-zinc-600">
      <div class="p-2 border-b border-b-zinc-700">
        <%= f.label :name, class: 'sr-only' %>

        <%= f.text_field :name,
            placeholder: 'Task name',
            autofocus: true,
            class: 'w-full bg-transparent border-none p-1 text-sm focus:outline-none focus:ring-0'
        %>

        <%= f.text_area :description,
            placeholder: 'Description',
            class: 'w-full bg-transparent border-none p-1 text-sm focus:outline-none focus:ring-0'
        %>
      </div>

      <div class="flex justify-end gap-3 p-2">
        <%= link_to 'Cancel',
            users_project_path(@project),
            class: 'bg-zinc-800 py-1.5 px-4 rounded text-sm'
        %>

        <%= f.button 'Save', class: 'bg-red-500 py-1.5 px-4 rounded text-sm' %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/users/tasks/new.html.erb
<%= turbo_frame_tag 'new_task_frame' do %>
  <%= render 'users/tasks/new/form', task: @task, project: @project %>
<% end %>

app/views/users/tasks/new/_form.html.erb
<%= form_for(task, url: users_project_tasks_path) do |f| %>
  <div class="rounded-xl border border-zinc-600">
    <div class="p-2 border-b border-b-zinc-700">
      <%= f.label :name, class: 'sr-only' %>

      <%= f.text_field :name,
          placeholder: 'Task name',
          autofocus: true,
          required: true,
          class: 'w-full bg-transparent border-none p-1 text-sm focus:outline-none focus:ring-0'
      %>

      <%= f.text_area :description,
          placeholder: 'Description',
          class: 'w-full bg-transparent border-none p-1 text-sm focus:outline-none focus:ring-0'
      %>
    </div>

    <div class="flex justify-end gap-3 p-2">
      <%= link_to 'Cancel',
          users_project_path(project),
          class: 'bg-zinc-800 py-1.5 px-4 rounded text-sm'
      %>

      <%= f.button 'Add Task', class: 'bg-red-500 py-1.5 px-4 rounded text-sm' %>
    </div>
  </div>
<% end %>

app/views/users/tasks/update.turbo_stream.erb
<%= turbo_stream.replace "tasks" do %>
  <%= render 'users/projects/tasks', tasks: @tasks %>
<% end %>